services:
  rn_irl:
    image: python:3.12-slim
    container_name: rn_irl
    working_dir: /app
    volumes:
      - ./:/app:rw
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLECORS=false
    command: /bin/sh -c "pip install --no-cache-dir -r requirements.txt && streamlit run rn_irl.py --server.port=8501 --server.headless=true --server.enableCORS=false"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8501/_stcore/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  sqlite3:
    image: alpine:3.20
    container_name: rn_irl_sqlite3
    command: ["/bin/sh", "-c", "apk add --no-cache sqlite && sqlite3 /data/irl.sdb"]
    volumes:
      - ./data:/data:rw
    profiles: ["tools"]

networks:
  default:
    name: rn_irl_net
